### ISSUE TITLE
Follow Electron's security guidance

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/browserd#17]
We should be doing the things called out in the [electron security docs](https://electronjs.org/docs/tutorial/security) as we're designed to load remote content, which could be insecure. ⚠

**Comment by phongcao** [comment]
[electronegativity](https://github.com/doyensec/electronegativity) is such a nice tool that we can use to spot security concerns.
To install:
```
npm install -g asar
npm install @doyensec/electronegativity -g
```
To run:
```
electronegativity -i .
```

![issues](https://user-images.githubusercontent.com/9741323/60369560-00f0d880-99c2-11e9-8ab9-6abbfc7b8d35.PNG)

**Comment by bengreenier** [comment]
that's awesome! can an action item for this work be to add that to run in our pipelines/build steps??

**Comment by phongcao** [comment]
Yes, I'd love to do so but right now it has some bugs on my machine so let me spend some more time to investigate.

**Comment by phongcao** [comment]
electronegativity v1.3 (latest) is using [typescript-estree](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/typescript-estree) to parse typescript files. The version of TypeScript currently supported by this parser is 3.2.1 while ours is 3.5.2. Besides, I tried downgrading our version to 3.2.1 and it's still not running well and caused some false alarms.
Therefore, I think that we still need to do manually validation for electron security issues and re-visit this tool in the future when it's mature enough. Right now, we can follow their awesome security checklist here:
https://doyensec.com/resources/us-17-Carettoni-Electronegativity-A-Study-Of-Electron-Security-wp.pdf
