### ISSUE TITLE
Repo restructuring to allow client creation 📊

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/browserd#24]
As discussed in person, we'll need to restructure this repository a bit, to facilitate adding an in-repo client (per #2).

We'll use the following structure:
```
.                 
├───shared            
├───stream-provider         
└───stream-consumer            
```
Where: 
+ `shared` houses shared logic (ie: `signal.ts`) and their tests
+ `stream-provider` houses streamer logic (the electron-renderer-enabled browser)
+ `stream-consumer` houses viewer logic (the new client we'll author)

The root will get a new readme clarifying these, and the existing codebase will move to `stream-provider`. This will require refactoring of CI/CD as well (using path filters in `pipelines.yaml` files).

The expected end result of this work is:

- [x] The existing codebase is migrated to `stream-provider`
- [ ] The existing CI/CD works, and is triggered only be changes to `stream-provider/**`
- [x] `signal.ts` and it's tests are moved to `shared` and consumed from there
- [x] `stream-provider` has a new readme
- [ ] `.` has a new readme, referencing the sub-directories content
- [x] `stream-consumer` has a new readme indicating it's goals

**Comment by conrad465** [comment]
Should changes to the shared repo trigger CI/CD for both provider and consumer since they are both dependent?

**Comment by bengreenier** [comment]
Yes - I think that makes sense, assuming we'll take hard references to `shared` from the other 2 (which i'm pretty sure we will, don't see a good alternative).

ie:

```
import { sharedThing } from "../shared/sharedThing";
```

**Comment by bengreenier** [comment]
closing with #37 - great work @conrad465 🎉
